const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  // Clear existing books
  await prisma.book.deleteMany({})

  const books = [
    // FICCIÓN (10)
    {
      title: '1984',
      author: 'George Orwell',
      genre: 'ficción',
      synopsis: 'Una novela distópica sobre un régimen totalitario y la lucha por la libertad individual.',
      difficulty: 'advanced',
      publicationYear: 1949,
      tags: ['distopia', 'política', 'futuro'],
    },
    {
      title: 'El Quijote',
      author: 'Miguel de Cervantes',
      genre: 'ficción',
      synopsis: 'Las aventuras de un caballero que pierde la cordura y cree ser un héroe de novelas de caballerías.',
      difficulty: 'advanced',
      publicationYear: 1605,
      tags: ['clásico', 'aventura', 'humor'],
    },
    {
      title: 'Cien años de soledad',
      author: 'Gabriel García Márquez',
      genre: 'ficción',
      synopsis: 'La saga familiar de los Buendía en el pueblo mágico de Macondo.',
      difficulty: 'intermediate',
      publicationYear: 1967,
      tags: ['realismo mágico', 'familia', 'latinoamérica'],
    },
    {
      title: 'El Hobbit',
      author: 'J.R.R. Tolkien',
      genre: 'fantasía',
      synopsis: 'Las aventuras de un hobbit en un viaje épico para recuperar un tesoro robado.',
      difficulty: 'intermediate',
      publicationYear: 1937,
      tags: ['fantasía', 'aventura', 'épica'],
    },
    {
      title: 'Orgullo y prejuicio',
      author: 'Jane Austen',
      genre: 'romance',
      synopsis: 'La historia de Elizabeth Bennet y su compleja relación con el Sr. Darcy.',
      difficulty: 'intermediate',
      publicationYear: 1813,
      tags: ['romance', 'clásico', 'sociedad'],
    },
    {
      title: 'Crimen y castigo',
      author: 'Fiódor Dostoievski',
      genre: 'misterio',
      synopsis: 'Un estudiante comete un crimen y luego lucha con la culpa y la moral.',
      difficulty: 'advanced',
      publicationYear: 1866,
      tags: ['misterio', 'psicología', 'moral'],
    },
    {
      title: 'El Gran Gatsby',
      author: 'F. Scott Fitzgerald',
      genre: 'ficción',
      synopsis: 'La trágica historia de un hombre obsesionado con recuperar su pasado.',
      difficulty: 'intermediate',
      publicationYear: 1925,
      tags: ['amor', 'tragedia', 'sueños'],
    },
    {
      title: 'Jane Eyre',
      author: 'Charlotte Brontë',
      genre: 'romance',
      synopsis: 'La vida de una mujer independiente que lucha por su amor verdadero.',
      difficulty: 'intermediate',
      publicationYear: 1847,
      tags: ['romance', 'independencia', 'clásico'],
    },
    {
      title: 'El Código Da Vinci',
      author: 'Dan Brown',
      genre: 'misterio',
      synopsis: 'Un viaje emocionante tras un misterio ancestral y secretos religiosos.',
      difficulty: 'beginner',
      publicationYear: 2003,
      tags: ['misterio', 'thriller', 'historia'],
    },
    {
      title: 'Dune',
      author: 'Frank Herbert',
      genre: 'ciencia ficción',
      synopsis: 'Una épica espacial sobre política, religión y control de un planeta desértico.',
      difficulty: 'advanced',
      publicationYear: 1965,
      tags: ['ciencia ficción', 'épica', 'política'],
    },
    // HISTORIA (10)
    {
      title: 'Sapiens',
      author: 'Yuval Noah Harari',
      genre: 'historia',
      synopsis: 'Una historia de la humanidad desde la Edad de Piedra hasta el presente.',
      difficulty: 'intermediate',
      publicationYear: 2011,
      tags: ['historia', 'antropología', 'sociedad'],
    },
    {
      title: 'La ruta de la seda',
      author: 'Peter Frankopan',
      genre: 'historia',
      synopsis: 'La historia olvidada de las antiguas rutas comerciales que conectaron el mundo.',
      difficulty: 'intermediate',
      publicationYear: 2015,
      tags: ['historia', 'comercio', 'geopolítica'],
    },
    {
      title: 'El mundo en llamas',
      author: 'Adam Tooze',
      genre: 'historia',
      synopsis: 'Una perspectiva económica de la Segunda Guerra Mundial.',
      difficulty: 'advanced',
      publicationYear: 2006,
      tags: ['historia', 'economía', 'guerra mundial'],
    },
    {
      title: 'Breve historia de casi todo',
      author: 'Bill Bryson',
      genre: 'historia',
      synopsis: 'Una exploración amena de cómo sabemos lo que sabemos sobre el mundo.',
      difficulty: 'beginner',
      publicationYear: 2003,
      tags: ['ciencia', 'historia', 'divulgación'],
    },
    {
      title: '1453: El último asedio',
      author: 'Roger Crowley',
      genre: 'historia',
      synopsis: 'La caída de Constantinopla y el fin del imperio bizantino.',
      difficulty: 'intermediate',
      publicationYear: 2005,
      tags: ['historia', 'imperio', 'guerra'],
    },
    {
      title: 'El siglo XX',
      author: 'Eric Hobsbawm',
      genre: 'historia',
      synopsis: 'Un análisis exhaustivo de los eventos que definieron el siglo XX.',
      difficulty: 'advanced',
      publicationYear: 1994,
      tags: ['historia', 'política', 'análisis'],
    },
    {
      title: 'Armas, acero y virus',
      author: 'Jared Diamond',
      genre: 'historia',
      synopsis: 'Por qué algunos pueblos conquistaron a otros: una exploración de la historia mundial.',
      difficulty: 'intermediate',
      publicationYear: 1997,
      tags: ['historia', 'antropología', 'geografía'],
    },
    {
      title: 'Los príncipes mercaderes',
      author: 'Fernand Braudel',
      genre: 'historia',
      synopsis: 'La historia del capitalismo mercantil en los siglos XVI-XVIII.',
      difficulty: 'advanced',
      publicationYear: 1979,
      tags: ['historia', 'economía', 'capitalismo'],
    },
    {
      title: 'Revolución rusa',
      author: 'Orlando Figes',
      genre: 'historia',
      synopsis: 'Una narrativa detallada de la Revolución Rusa y sus consecuencias.',
      difficulty: 'advanced',
      publicationYear: 1996,
      tags: ['historia', 'revolución', 'política'],
    },
    {
      title: 'La peste negra',
      author: 'William H. McNeill',
      genre: 'historia',
      synopsis: 'Cómo las plagas moldearon la historia de la humanidad.',
      difficulty: 'intermediate',
      publicationYear: 1976,
      tags: ['historia', 'enfermedad', 'sociedad'],
    },
    // DESARROLLO PERSONAL (10)
    {
      title: 'Hábitos atómicos',
      author: 'James Clear',
      genre: 'desarrollo',
      synopsis: 'Cómo pequeños cambios conducen a resultados extraordinarios.',
      difficulty: 'beginner',
      publicationYear: 2018,
      tags: ['hábitos', 'productividad', 'crecimiento'],
    },
    {
      title: 'Deep Work',
      author: 'Cal Newport',
      genre: 'desarrollo',
      synopsis: 'El poder de concentrarse en tareas importantes en una economía distraída.',
      difficulty: 'beginner',
      publicationYear: 2016,
      tags: ['productividad', 'enfoque', 'trabajo'],
    },
    {
      title: 'Mindset',
      author: 'Carol Dweck',
      genre: 'desarrollo',
      synopsis: 'La psicología del éxito: mentalidad fija vs mentalidad de crecimiento.',
      difficulty: 'beginner',
      publicationYear: 2006,
      tags: ['psicología', 'crecimiento', 'mentalidad'],
    },
    {
      title: 'El hábito del poder',
      author: 'Tony Schwartz',
      genre: 'desarrollo',
      synopsis: 'Cómo gestionar la energía para maximizar el rendimiento.',
      difficulty: 'beginner',
      publicationYear: 2007,
      tags: ['energía', 'productividad', 'bienestar'],
    },
    {
      title: 'Inteligencia emocional',
      author: 'Daniel Goleman',
      genre: 'desarrollo',
      synopsis: 'Por qué la inteligencia emocional es más importante que el cociente intelectual.',
      difficulty: 'intermediate',
      publicationYear: 1995,
      tags: ['emociones', 'inteligencia', 'relaciones'],
    },
    {
      title: 'El camino menos transitado',
      author: 'M. Scott Peck',
      genre: 'desarrollo',
      synopsis: 'Una guía para el crecimiento espiritual y la autosuperación.',
      difficulty: 'intermediate',
      publicationYear: 1978,
      tags: ['crecimiento', 'espiritualidad', 'psicología'],
    },
    {
      title: 'Los 7 hábitos de la gente altamente efectiva',
      author: 'Stephen Covey',
      genre: 'desarrollo',
      synopsis: 'Principios fundamentales para la efectividad personal e interpersonal.',
      difficulty: 'intermediate',
      publicationYear: 1989,
      tags: ['hábitos', 'efectividad', 'liderazgo'],
    },
    {
      title: 'El poder del ahora',
      author: 'Eckhart Tolle',
      genre: 'desarrollo',
      synopsis: 'Cómo vivir en el presente y liberarse del estrés mental.',
      difficulty: 'intermediate',
      publicationYear: 1997,
      tags: ['presente', 'mindfulness', 'espiritualidad'],
    },
    {
      title: 'Flujo: La psicología de la experiencia óptima',
      author: 'Mihaly Csikszentmihalyi',
      genre: 'desarrollo',
      synopsis: 'Cómo alcanzar estados de completa absorción y felicidad.',
      difficulty: 'intermediate',
      publicationYear: 1990,
      tags: ['psicología', 'felicidad', 'flujo'],
    },
    {
      title: 'Pensar rápido, pensar lento',
      author: 'Daniel Kahneman',
      genre: 'desarrollo',
      synopsis: 'Cómo funcionan dos sistemas de pensamiento y cómo mejoran tus decisiones.',
      difficulty: 'advanced',
      publicationYear: 2011,
      tags: ['psicología', 'decisiones', 'cognición'],
    },
    // FILOSOFÍA (10)
    {
      title: 'Crítica de la razón pura',
      author: 'Immanuel Kant',
      genre: 'filosofía',
      synopsis: 'La obra fundamental sobre los límites del conocimiento humano.',
      difficulty: 'advanced',
      publicationYear: 1781,
      tags: ['filosofía', 'epistemología', 'clásico'],
    },
    {
      title: 'El ser y la nada',
      author: 'Jean-Paul Sartre',
      genre: 'filosofía',
      synopsis: 'Una exploración del existencialismo y la libertad humana.',
      difficulty: 'advanced',
      publicationYear: 1943,
      tags: ['existencialismo', 'libertad', 'responsabilidad'],
    },
    {
      title: 'República',
      author: 'Platón',
      genre: 'filosofía',
      synopsis: 'El diálogo sobre justicia y la naturaleza del Estado ideal.',
      difficulty: 'advanced',
      publicationYear: -380,
      tags: ['filosofía', 'política', 'clásico greco-romano'],
    },
    {
      title: 'Ética a Nicómaco',
      author: 'Aristóteles',
      genre: 'filosofía',
      synopsis: 'La base de la ética occidental y el concepto de virtud.',
      difficulty: 'advanced',
      publicationYear: -325,
      tags: ['ética', 'virtud', 'clásico greco-romano'],
    },
    {
      title: 'El contrato social',
      author: 'Jean-Jacques Rousseau',
      genre: 'filosofía',
      synopsis: 'Una teoría sobre la legitimidad del poder político basada en acuerdos.',
      difficulty: 'advanced',
      publicationYear: 1762,
      tags: ['filosofía política', 'libertad', 'sociedad'],
    },
    {
      title: 'Así habló Zaratustra',
      author: 'Friedrich Nietzsche',
      genre: 'filosofía',
      synopsis: 'Una novela filosófica sobre la reivindicación del poder y la libertad.',
      difficulty: 'advanced',
      publicationYear: 1885,
      tags: ['filosofía', 'poder', 'humanidad'],
    },
    {
      title: 'La riqueza de las naciones',
      author: 'Adam Smith',
      genre: 'filosofía',
      synopsis: 'Los fundamentos de la economía moderna y el capitalismo.',
      difficulty: 'intermediate',
      publicationYear: 1776,
      tags: ['economía', 'filosofía política', 'capitalismo'],
    },
    {
      title: 'Fenomenología del espíritu',
      author: 'Georg Wilhelm Friedrich Hegel',
      genre: 'filosofía',
      synopsis: 'Un estudio de la conciencia y su desarrollo histórico.',
      difficulty: 'advanced',
      publicationYear: 1807,
      tags: ['fenomenología', 'conciencia', 'historia'],
    },
    {
      title: 'El mito de Sísifo',
      author: 'Albert Camus',
      genre: 'filosofía',
      synopsis: 'Un ensayo sobre el absurdo de la existencia humana.',
      difficulty: 'intermediate',
      publicationYear: 1942,
      tags: ['absurdo', 'existencia', 'sentido'],
    },
    {
      title: 'Investigaciones filosóficas',
      author: 'Ludwig Wittgenstein',
      genre: 'filosofía',
      synopsis: 'Una revolución en la filosofía del lenguaje y la lógica.',
      difficulty: 'advanced',
      publicationYear: 1953,
      tags: ['lenguaje', 'lógica', 'filosofía analítica'],
    },
    // CIENCIA (10)
    {
      title: 'El gen egoísta',
      author: 'Richard Dawkins',
      genre: 'ciencia',
      synopsis: 'Una perspectiva revolucionaria sobre la evolución desde el punto de vista genético.',
      difficulty: 'intermediate',
      publicationYear: 1976,
      tags: ['biología', 'evolución', 'genes'],
    },
    {
      title: 'Astrofísica para apresuraciones',
      author: 'Neil deGrasse Tyson',
      genre: 'ciencia',
      synopsis: 'Una introducción amena a los grandes misterios del universo.',
      difficulty: 'beginner',
      publicationYear: 2017,
      tags: ['astronomía', 'física', 'divulgación'],
    },
    {
      title: 'La vida secreta de las plantas',
      author: 'Peter Tompkins & Christopher Bird',
      genre: 'ciencia',
      synopsis: 'Investigaciones sobre las capacidades sensitivas de las plantas.',
      difficulty: 'beginner',
      publicationYear: 1973,
      tags: ['botánica', 'naturaleza', 'investigación'],
    },
    {
      title: 'Humanos como especie',
      author: 'Juan Luis Arsuaga',
      genre: 'ciencia',
      synopsis: 'La historia de la evolución humana basada en hallazgos antropológicos.',
      difficulty: 'intermediate',
      publicationYear: 1999,
      tags: ['antropología', 'evolución', 'humanos'],
    },
    {
      title: 'El universo en una cáscara de nuez',
      author: 'Stephen Hawking',
      genre: 'ciencia',
      synopsis: 'Una exploración de la física moderna y los misterios del universo.',
      difficulty: 'intermediate',
      publicationYear: 2001,
      tags: ['física', 'cosmología', 'universo'],
    },
    {
      title: 'Biología del cuerpo',
      author: 'Antonio Damasio',
      genre: 'ciencia',
      synopsis: 'Cómo el cuerpo y las emociones moldean el cerebro y la conciencia.',
      difficulty: 'advanced',
      publicationYear: 1994,
      tags: ['neurociencia', 'biología', 'conciencia'],
    },
    {
      title: 'El código de la vida',
      author: 'Francis Collins',
      genre: 'ciencia',
      synopsis: 'El desciframiento del genoma humano y sus implicaciones.',
      difficulty: 'intermediate',
      publicationYear: 2006,
      tags: ['genética', 'biología', 'ADN'],
    },
    {
      title: 'Cómo funciona el cerebro',
      author: 'John Medina',
      genre: 'ciencia',
      synopsis: 'Los principios de cómo el cerebro aprende y recuerda.',
      difficulty: 'beginner',
      publicationYear: 2008,
      tags: ['neurociencia', 'cerebro', 'aprendizaje'],
    },
    {
      title: 'La mente cristalina',
      author: 'V.S. Ramachandran',
      genre: 'ciencia',
      synopsis: 'Viajes extraordinarios dentro del cerebro.',
      difficulty: 'intermediate',
      publicationYear: 1998,
      tags: ['neurociencia', 'cerebro', 'percepto'],
    },
    {
      title: 'Origen de las especies',
      author: 'Charles Darwin',
      genre: 'ciencia',
      synopsis: 'La teoría fundamental de la evolución biológica.',
      difficulty: 'advanced',
      publicationYear: 1859,
      tags: ['evolución', 'biología', 'clásico'],
    },
    // GÉNEROS MIXTOS (10)
    {
      title: 'El Príncipe',
      author: 'Nicolás Maquiavelo',
      genre: 'política',
      synopsis: 'Un tratado sobre el poder político y cómo mantenerlo.',
      difficulty: 'intermediate',
      publicationYear: 1532,
      tags: ['política', 'poder', 'estrategia'],
    },
    {
      title: 'En busca del tiempo perdido',
      author: 'Marcel Proust',
      genre: 'ficción',
      synopsis: 'Una introspección profunda sobre la memoria y el tiempo.',
      difficulty: 'advanced',
      publicationYear: 1927,
      tags: ['memoria', 'tiempo', 'introspección'],
    },
    {
      title: 'El Mahabharata',
      author: 'Veda Vyasa',
      genre: 'poesía',
      synopsis: 'La epopeya hindú más antigua sobre una batalla y el dharma.',
      difficulty: 'advanced',
      publicationYear: -400,
      tags: ['épica', 'hinduismo', 'mitología'],
    },
    {
      title: 'Don Quijote de la Mancha (Segunda parte)',
      author: 'Miguel de Cervantes',
      genre: 'ficción',
      synopsis: 'Las nuevas aventuras del caballero en su lucha contra los molinos de viento.',
      difficulty: 'advanced',
      publicationYear: 1615,
      tags: ['aventura', 'humor', 'clásico'],
    },
    {
      title: 'La montaña mágica',
      author: 'Thomas Mann',
      genre: 'ficción',
      synopsis: 'La vida en un sanatorio de montaña y sus personajes.',
      difficulty: 'advanced',
      publicationYear: 1924,
      tags: ['filosofía', 'existencia', 'tiempo'],
    },
    {
      title: 'Ulises',
      author: 'James Joyce',
      genre: 'ficción',
      synopsis: 'Un día en la vida de Leopold Bloom en Dublín, en paralelo a La Odisea.',
      difficulty: 'advanced',
      publicationYear: 1922,
      tags: ['clásico moderno', 'Dublín', 'experimentación'],
    },
    {
      title: 'Cien años de soledad (Reedición)',
      author: 'Gabriel García Márquez',
      genre: 'ficción',
      synopsis: 'Reedición especial con comentarios sobre la magia de Macondo.',
      difficulty: 'intermediate',
      publicationYear: 1987,
      tags: ['realismo mágico', 'familia', 'clásico'],
    },
    {
      title: 'El retrato de Dorian Gray',
      author: 'Oscar Wilde',
      genre: 'ficción',
      synopsis: 'La historia de un hombre obsesionado con la belleza y la juventud eterna.',
      difficulty: 'intermediate',
      publicationYear: 1890,
      tags: ['vanidad', 'belleza', 'corrupción'],
    },
    {
      title: 'El público lector',
      author: 'Alberto Manguel',
      genre: 'ensayo',
      synopsis: 'Una historia de la lectura y los lectores a través del tiempo.',
      difficulty: 'intermediate',
      publicationYear: 1998,
      tags: ['lectura', 'historia', 'cultura'],
    },
    {
      title: 'La noche boreal',
      author: 'Knut Hamsun',
      genre: 'ficción',
      synopsis: 'La vida de un hombre en el Ártico durante la noche polar.',
      difficulty: 'intermediate',
      publicationYear: 1888,
      tags: ['naturaleza', 'soledad', 'introspección'],
    },
  ]

  console.log(`Seeding ${books.length} books...`)

  for (const book of books) {
    await prisma.book.create({
      data: book,
    })
  }

  console.log('✅ Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
