import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Clear existing books
  await prisma.book.deleteMany({});

  const books = [
    // FICCIÓN (10 books)
    {
      title: '1984',
      author: 'George Orwell',
      genre: 'ficción',
      difficulty: 'advanced',
      synopsis: 'Una novela distópica sobre un régimen totalitario que controla cada aspecto de la vida de sus ciudadanos.',
      publicationYear: 1949,
      tags: ['dystopía', 'political', 'oscuro'],
    },
    {
      title: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'La historia de Kvothe, un mago legendario, narrada a través de sus memorias en una posada remota.',
      publicationYear: 2007,
      tags: ['fantasía', 'magia', 'aventura'],
    },
    {
      title: 'El Quijote',
      author: 'Miguel de Cervantes',
      genre: 'ficción',
      difficulty: 'advanced',
      synopsis: 'Las aventuras de un hidalgo que pierde la razón y se cree un caballero andante.',
      publicationYear: 1605,
      tags: ['clásico', 'aventura', 'satírico'],
    },
    {
      title: 'Cien años de soledad',
      author: 'Gabriel García Márquez',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'La historia de la familia Buendía a través de cien años en el pueblo ficticio de Macondo.',
      publicationYear: 1967,
      tags: ['realismo mágico', 'familia', 'drama'],
    },
    {
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'La historia de Elizabeth Bennet y su romance con el señor Darcy en la Inglaterra del siglo XIX.',
      publicationYear: 1813,
      tags: ['romance', 'clásico', 'sociedad'],
    },
    {
      title: 'La sombra del viento',
      author: 'Carlos Ruiz Zafón',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'Un misterio literario ambientado en Barcelona, donde un chico descubre un libro en el Cementerio de los Libros Olvidados.',
      publicationYear: 2001,
      tags: ['misterio', 'romántico', 'Barcelona'],
    },
    {
      title: 'The Great Gatsby',
      author: 'F. Scott Fitzgerald',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'La historia de Jay Gatsby y su obsesión por recuperar el amor perdido en los años veinte americanos.',
      publicationYear: 1925,
      tags: ['clásico', 'romance', 'drama'],
    },
    {
      title: 'Mujercitas',
      author: 'Louisa May Alcott',
      genre: 'ficción',
      difficulty: 'beginner',
      synopsis: 'Las aventuras de cuatro hermanas durante la Guerra Civil Americana.',
      publicationYear: 1868,
      tags: ['clásico', 'familia', 'juventud'],
    },
    {
      title: 'Demian',
      author: 'Hermann Hesse',
      genre: 'ficción',
      difficulty: 'intermediate',
      synopsis: 'Una novela sobre el viaje de autoaprendizaje y la búsqueda de identidad de un joven.',
      publicationYear: 1919,
      tags: ['psicológico', 'crecimiento', 'existencial'],
    },
    {
      title: 'The Hobbit',
      author: 'J.R.R. Tolkien',
      genre: 'ficción',
      difficulty: 'beginner',
      synopsis: 'Las aventuras de Bilbo Bolsón, un hobbit que es arrastrado a una épica aventura fantástica.',
      publicationYear: 1937,
      tags: ['fantasía', 'aventura', 'épico'],
    },

    // HISTORIA (10 books)
    {
      title: 'Sapiens',
      author: 'Yuval Noah Harari',
      genre: 'historia',
      difficulty: 'advanced',
      synopsis: 'Un recorrido por la historia de la humanidad desde el surgimiento del Homo sapiens hasta la actualidad.',
      publicationYear: 2011,
      tags: ['antropología', 'evolución', 'sociedad'],
    },
    {
      title: 'La peste negra',
      author: 'William H. McNeill',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'Historia de cómo las epidemias han moldeado la civilización humana.',
      publicationYear: 1976,
      tags: ['epidemias', 'sociedad', 'medicina'],
    },
    {
      title: 'Breve historia de casi todo',
      author: 'Bill Bryson',
      genre: 'historia',
      difficulty: 'beginner',
      synopsis: 'Una exploración amena de la ciencia, la naturaleza y la historia del universo.',
      publicationYear: 2003,
      tags: ['ciencia', 'divulgación', 'entretenido'],
    },
    {
      title: 'El Renacimiento',
      author: 'Peter Burke',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'Un análisis del movimiento cultural y artístico que transformó Europa.',
      publicationYear: 1997,
      tags: ['arte', 'cultura', 'Europa'],
    },
    {
      title: 'The Silk Roads',
      author: 'Peter Frankopan',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'La historia de las rutas de la seda y su impacto en la civilización mundial.',
      publicationYear: 2015,
      tags: ['comercio', 'culturas', 'viajes'],
    },
    {
      title: 'A Brief History of Time',
      author: 'Stephen Hawking',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'Una introducción accesible a los conceptos fundamentales de la cosmología y la física moderna.',
      publicationYear: 1988,
      tags: ['física', 'cosmos', 'ciencia'],
    },
    {
      title: 'La caída del Imperio Romano',
      author: 'Edward Gibbon',
      genre: 'historia',
      difficulty: 'advanced',
      synopsis: 'Un análisis profundo de las causas y consecuencias de la caída del Imperio Romano de Occidente.',
      publicationYear: 1776,
      tags: ['Imperio', 'declive', 'política'],
    },
    {
      title: 'Guns, Germs, and Steel',
      author: 'Jared Diamond',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'Un análisis de cómo la geografía y la ecología han moldeado el destino de las civilizaciones.',
      publicationYear: 1997,
      tags: ['geografía', 'evolución', 'sociedad'],
    },
    {
      title: 'La Revolución Francesa',
      author: 'Simon Schama',
      genre: 'historia',
      difficulty: 'advanced',
      synopsis: 'Una narrativa épica de los eventos que transformaron Francia y el mundo.',
      publicationYear: 1989,
      tags: ['revolución', 'política', 'Francia'],
    },
    {
      title: 'Cosmos',
      author: 'Carl Sagan',
      genre: 'historia',
      difficulty: 'intermediate',
      synopsis: 'Un viaje a través del universo, la ciencia y nuestro lugar en la naturaleza.',
      publicationYear: 1980,
      tags: ['astronomía', 'universo', 'filosofía'],
    },

    // DESARROLLO (10 books)
    {
      title: 'Hábitos atómicos',
      author: 'James Clear',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo pequeños cambios pueden llevar a resultados notables en tu vida.',
      publicationYear: 2018,
      tags: ['productividad', 'psicología', 'crecimiento'],
    },
    {
      title: 'Thinking, Fast and Slow',
      author: 'Daniel Kahneman',
      genre: 'desarrollo',
      difficulty: 'advanced',
      synopsis: 'Exploración de cómo funcionan dos sistemas de pensamiento en nuestro cerebro.',
      publicationYear: 2011,
      tags: ['psicología', 'cognición', 'decisiones'],
    },
    {
      title: 'El poder del hábito',
      author: 'Charles Duhigg',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo entender y cambiar nuestros hábitos cotidianos.',
      publicationYear: 2012,
      tags: ['productividad', 'psicología', 'comportamiento'],
    },
    {
      title: 'Mindset',
      author: 'Carol S. Dweck',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo nuestra mentalidad afecta al éxito y el crecimiento personal.',
      publicationYear: 2006,
      tags: ['psicología', 'crecimiento', 'educación'],
    },
    {
      title: 'Deep Work',
      author: 'Cal Newport',
      genre: 'desarrollo',
      difficulty: 'intermediate',
      synopsis: 'Cómo lograr concentración profunda en un mundo lleno de distracciones.',
      publicationYear: 2016,
      tags: ['productividad', 'enfoque', 'trabajo'],
    },
    {
      title: 'El Coraje de Ser Imperfecto',
      author: 'Brené Brown',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo abrirse emocionalmente y vivir con autenticidad.',
      publicationYear: 2012,
      tags: ['emociones', 'autoayuda', 'vulnerabilidad'],
    },
    {
      title: 'Cómo hablar para que los niños escuchen',
      author: 'Adele Faber y Elaine Mazlish',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Técnicas prácticas de comunicación efectiva con niños.',
      publicationYear: 1980,
      tags: ['parenting', 'comunicación', 'familia'],
    },
    {
      title: 'El éxito según Steve Jobs',
      author: 'Walter Isaacson',
      genre: 'desarrollo',
      difficulty: 'intermediate',
      synopsis: 'Lecciones de liderazgo e innovación de la vida de Steve Jobs.',
      publicationYear: 2011,
      tags: ['liderazgo', 'innovación', 'biografía'],
    },
    {
      title: 'Ikigai',
      author: 'Héctor García y Francesc Miralles',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo encontrar tu propósito y vivir una vida significativa.',
      publicationYear: 2016,
      tags: ['propósito', 'bienestar', 'filosofía'],
    },
    {
      title: 'Steal Like an Artist',
      author: 'Austin Kleon',
      genre: 'desarrollo',
      difficulty: 'beginner',
      synopsis: 'Cómo encontrar inspiración y desarrollar tu voz creativa.',
      publicationYear: 2012,
      tags: ['creatividad', 'arte', 'inspiración'],
    },

    // FILOSOFÍA (10 books)
    {
      title: 'Critique of Pure Reason',
      author: 'Immanuel Kant',
      genre: 'filosofía',
      difficulty: 'advanced',
      synopsis: 'Una obra fundamental de la filosofía que examina los límites del conocimiento humano.',
      publicationYear: 1781,
      tags: ['epistemología', 'metafísica', 'clásico'],
    },
    {
      title: 'El ser y la nada',
      author: 'Jean-Paul Sartre',
      genre: 'filosofía',
      difficulty: 'advanced',
      synopsis: 'Tratado fundamental del existencialismo sobre la libertad y responsabilidad humana.',
      publicationYear: 1943,
      tags: ['existencialismo', 'libertad', 'responsabilidad'],
    },
    {
      title: 'Meditations',
      author: 'Marcus Aurelius',
      genre: 'filosofía',
      difficulty: 'intermediate',
      synopsis: 'Reflexiones personales de un emperador romano sobre el estoicismo y la virtud.',
      publicationYear: 170,
      tags: ['estoicismo', 'ética', 'clásico'],
    },
    {
      title: 'The Republic',
      author: 'Plato',
      genre: 'filosofía',
      difficulty: 'advanced',
      synopsis: 'Diálogos de Platón sobre justicia, el estado ideal y la naturaleza de la realidad.',
      publicationYear: 380,
      tags: ['política', 'justicia', 'clásico'],
    },
    {
      title: 'Thus Spoke Zarathustra',
      author: 'Friedrich Nietzsche',
      genre: 'filosofía',
      difficulty: 'advanced',
      synopsis: 'Novela filosófica sobre la transvaloración de valores y el superhombre.',
      publicationYear: 1883,
      tags: ['existencialismo', 'moral', 'búsqueda'],
    },
    {
      title: 'El arte de la vida',
      author: 'Hubert Dreyfus',
      genre: 'filosofía',
      difficulty: 'intermediate',
      synopsis: 'Exploración de cómo vivir una vida auténtica y significativa.',
      publicationYear: 2009,
      tags: ['ética', 'autenticidad', 'vida'],
    },
    {
      title: 'Sophie\'s World',
      author: 'Jostein Gaarder',
      genre: 'filosofía',
      difficulty: 'intermediate',
      synopsis: 'Una novela que introduce la historia de la filosofía occidental a través de una misterio.',
      publicationYear: 1991,
      tags: ['historia', 'educación', 'novela'],
    },
    {
      title: 'Introducción a la fenomenología',
      author: 'Edmund Husserl',
      genre: 'filosofía',
      difficulty: 'advanced',
      synopsis: 'Análisis de la conciencia y la experiencia vivida.',
      publicationYear: 1931,
      tags: ['fenomenología', 'conciencia', 'epistemología'],
    },
    {
      title: 'The Ethics of Care',
      author: 'Nel Noddings',
      genre: 'filosofía',
      difficulty: 'intermediate',
      synopsis: 'Una perspectiva ética basada en el cuidado y las relaciones humanas.',
      publicationYear: 1984,
      tags: ['ética', 'cuidado', 'relaciones'],
    },
    {
      title: 'Analectas',
      author: 'Confucio',
      genre: 'filosofía',
      difficulty: 'intermediate',
      synopsis: 'Enseñanzas del filósofo chino sobre la virtud, la familia y el gobierno.',
      publicationYear: 475,
      tags: ['sabiduría', 'ética', 'clásico'],
    },

    // CIENCIA (10 books)
    {
      title: 'El gen egoísta',
      author: 'Richard Dawkins',
      genre: 'ciencia',
      difficulty: 'advanced',
      synopsis: 'Una perspectiva revolucionaria de la evolución centrada en el gen como unidad de selección.',
      publicationYear: 1976,
      tags: ['biología', 'evolución', 'genética'],
    },
    {
      title: 'La estructura de las revoluciones científicas',
      author: 'Thomas Kuhn',
      genre: 'ciencia',
      difficulty: 'advanced',
      synopsis: 'Análisis de cómo avanzan los paradigmas científicos y cambian las visiones del mundo.',
      publicationYear: 1962,
      tags: ['filosofía', 'historia', 'ciencia'],
    },
    {
      title: 'Astrophysics for People in a Hurry',
      author: 'Neil deGrasse Tyson',
      genre: 'ciencia',
      difficulty: 'beginner',
      synopsis: 'Una introducción rápida y amena a la astrofísica y el universo.',
      publicationYear: 2017,
      tags: ['astronomía', 'divulgación', 'universo'],
    },
    {
      title: 'The Selfish Gene',
      author: 'Richard Dawkins',
      genre: 'ciencia',
      difficulty: 'intermediate',
      synopsis: 'Cómo los genes influyen en el comportamiento animal y humano.',
      publicationYear: 1976,
      tags: ['biología', 'genética', 'comportamiento'],
    },
    {
      title: 'Life on the Edge',
      author: 'Jim Al-Khalili',
      genre: 'ciencia',
      difficulty: 'intermediate',
      synopsis: 'Cómo la mecánica cuántica juega un papel en la biología y la vida.',
      publicationYear: 2014,
      tags: ['física', 'biología', 'cuántica'],
    },
    {
      title: 'Sapiens: Digital',
      author: 'Yuval Noah Harari',
      genre: 'ciencia',
      difficulty: 'intermediate',
      synopsis: 'Cómo la tecnología digital está transformando la humanidad.',
      publicationYear: 2018,
      tags: ['tecnología', 'sociedad', 'futuro'],
    },
    {
      title: 'The Immortal Life of Henrietta Lacks',
      author: 'Rebecca Skloot',
      genre: 'ciencia',
      difficulty: 'beginner',
      synopsis: 'La historia de una mujer cuyas células revolucionaron la medicina moderna.',
      publicationYear: 2010,
      tags: ['medicina', 'ética', 'biografía'],
    },
    {
      title: 'Complexity',
      author: 'M. Mitchell Waldrop',
      genre: 'ciencia',
      difficulty: 'intermediate',
      synopsis: 'Introducción a la teoría de sistemas complejos.',
      publicationYear: 1992,
      tags: ['complejidad', 'sistemas', 'ciencia'],
    },
    {
      title: 'Antifragile',
      author: 'Nassim Nicholas Taleb',
      genre: 'ciencia',
      difficulty: 'advanced',
      synopsis: 'Cómo prosperar y crecer ante la incertidumbre y el caos.',
      publicationYear: 2012,
      tags: ['riesgo', 'volatilidad', 'filosofía'],
    },
    {
      title: 'El tejido de la vida',
      author: 'Fritjof Capra',
      genre: 'ciencia',
      difficulty: 'intermediate',
      synopsis: 'Una visión sistémica de la vida y la naturaleza.',
      publicationYear: 1996,
      tags: ['ecología', 'sistemas', 'filosofía'],
    },
  ];

  console.log(`Iniciando creación de ${books.length} libros...`);

  for (const book of books) {
    const created = await prisma.book.create({
      data: book,
    });
    console.log(`✓ Creado: ${created.title} by ${created.author}`);
  }

  console.log('✓ Semilla completada! 60 libros han sido creados.');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('Error durante la semilla:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
